#pragma once

#pragma warning(disable: 4251)

#ifdef INFINITYOFFICIALNETWORKMEDIASERVERNATIVECORE_EXPORTS
#define __INFINITYOFFICIALNETWORK_MEDIASERVER_NATIVE_CORE_API __declspec(dllexport)
#else
#define __INFINITYOFFICIALNETWORK_MEDIASERVER_NATIVE_CORE_API __declspec(dllimport)
#endif
