#pragma once

#pragma warning(disable: 4251)

#ifdef __INFINITYOFFICIALNETWORK_MEDIASERVER_NATIVE_CORE_SHARED_EXPORTS
#define __INFINITYOFFICIALNETWORK_MEDIASERVER_NATIVE_CORE_SHARED_API __declspec(dllexport)
#else
#define __INFINITYOFFICIALNETWORK_MEDIASERVER_NATIVE_CORE_SHARED_API __declspec(dllimport)
#endif


